Vagrant.configure("2") do |config|
config.vm.define :haproxy do |haproxy|
haproxy.vm.box = "bento/ubuntu-20.04"
haproxy.vm.network :private_network, ip: "192.168.100.2"
haproxy.vm.provision "shell", path: "haproxy.sh"
haproxy.vm.hostname = "haproxy"
end
config.vm.define :web1 do |web1|
web1.vm.box = "bento/ubuntu-20.04"
web1.vm.network :private_network, ip: "192.168.100.3"
web1.vm.provision "shell", path: "web1.sh"
web1.vm.hostname = "web1"
end
config.vm.define :web2 do |web2|
web2.vm.box = "bento/ubuntu-20.04"
web2.vm.network :private_network, ip: "192.168.100.4"
web2.vm.provision "shell", path: "web2.sh"
web2.vm.hostname = "web2"
end
config.vm.define :web1backup do |web1backup|
web1backup.vm.box = "bento/ubuntu-20.04"
web1backup.vm.network :private_network, ip: "192.168.100.5"
web1backup.vm.provision "shell", path: "web1backup.sh"
web1backup.vm.hostname = "web1backup"
end
config.vm.define :web2backup do |web2backup|
web2backup.vm.box = "bento/ubuntu-20.04"
web2backup.vm.network :private_network, ip: "192.168.100.6"
web2backup.vm.provision "shell", path: "web2backup.sh"
web2backup.vm.hostname = "web2backup"
end
end